version: '3.7'
services:
  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --address :9000 --console-address :9001

  node_app:
    build:
      context: .
      dockerfile: node/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    environment:
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_SSL: "false"
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    depends_on:
      - minio

volumes:
  minio_data: